SET IDENTITY_INSERT [dbo].[AddaLife] ON
INSERT INTO [dbo].[AddaLife] ([ID], [Title], [First_Name], [Surname], [Initials], [dob], [Gender], [ID_number], [Relationship], [Comm_date]) VALUES (2, N'Mr', N'Maelfa', N'Zulu', N'M', N'2000/01/01', N'Male', N'0001010434080', N'Child', N'01/01/2022')
INSERT INTO [dbo].[AddaLife] ([ID], [Title], [First_Name], [Surname], [Initials], [dob], [Gender], [ID_number], [Relationship], [Comm_date]) VALUES (3, N'oijokko]p[[okniun', N'wehuc7dsbew', N'iw', N'nciudw', N'nc', N'cdiud', N'ncpijd', N'cniscnijw', N'nx')
INSERT INTO [dbo].[AddaLife] ([ID], [Title], [First_Name], [Surname], [Initials], [dob], [Gender], [ID_number], [Relationship], [Comm_date]) VALUES (4, N'oijokko]p[[okniun', N'wehuc7dsbew', N'iw', N'nciudw', N'nc', N'cdiud', N'ncpijd', N'cniscnijw', N'nx')
INSERT INTO [dbo].[AddaLife] ([ID], [Title], [First_Name], [Surname], [Initials], [dob], [Gender], [ID_number], [Relationship], [Comm_date]) VALUES (5, N'oijokko]p[[okniun', N'wehuc7dsbew', N'iw', N'nciudw', N'nc', N'cdiud', N'ncpijd', N'cniscnijw', N'nx8udcuebj')
INSERT INTO [dbo].[AddaLife] ([ID], [Title], [First_Name], [Surname], [Initials], [dob], [Gender], [ID_number], [Relationship], [Comm_date]) VALUES (6, N'oijokko]p[[okniun', N'wehuc7dsbew', N'iwnin', N'nciudwipnpi', N'ncinjlk', N'cdiud', N'ncpijd', N'cniscnijw', N'nx8udcuebj')
INSERT INTO [dbo].[AddaLife] ([ID], [Title], [First_Name], [Surname], [Initials], [dob], [Gender], [ID_number], [Relationship], [Comm_date]) VALUES (7, N'pl,ifdjvu8uchuw', N'uhubh', N'ubyy7yv', N'bvghubijbyub', N'ygviygivib', N'yg viyg', N'bhbhu yg', N'ygiygbb', N'hubh nj ')
INSERT INTO [dbo].[AddaLife] ([ID], [Title], [First_Name], [Surname], [Initials], [dob], [Gender], [ID_number], [Relationship], [Comm_date]) VALUES (8, N'iuhuuij', N'jchubqdhub', N'dw wuchuc', N'uchwuch', N'wuchwuh', N'wucwc8u', N'wuec8uc', N'wehbewcb', N'2hubwhb')
INSERT INTO [dbo].[AddaLife] ([ID], [Title], [First_Name], [Surname], [Initials], [dob], [Gender], [ID_number], [Relationship], [Comm_date]) VALUES (9, N'ufgghkj', N'hufyuhgoi', N'hghu;kj', N'yearstdoij', N'tewarstdyugijo', N'erstdyugi', N'arestdyugi', N'eryugoij', N'lowner')
SET IDENTITY_INSERT [dbo].[AddaLife] OFF
