INSERT INTO ProvideProtect (Age,
Policy_Fee,
LifeCover_RateGroup1_Male,
LifeCover_RateGroup2_Male,
LifeCover_RateGroup3_Male,
LifeCover_RateGroup4_Male,
LifeCover_RateGroup1_Female,
LifeCover_RateGroup2_Female,
LifeCover_LifeCover_RateGroup3_Female,
RateGroup4_Female,PIMain_OccClassA_Male,
PIMain_OccClassB_Male,
PIMain_OccClassC_Male,
PIMain_OccClassD_Male,
PIMain_OccClassE_Male,
PIMain_OccClassA_Female,
PIMain_OccClassB_Female,
PIMain_OccClassC_Female,
PIMain_OccClassD_Female,
PIMain_OccClassE_Female,
DreadDiseasePLA_RateGroup1_Male,
DreadDiseasePLA_RateGroup2_Male,
DreadDiseasePLA_RateGroup3_Male,
DreadDiseasePLA_RateGroup4_Male,
DreadDiseasePLA_RateGroup1_Female,
DreadDiseasePLA_RateGroup2_Female,
DreadDiseasePLA_RateGroup3_Female,
DreadDiseasePLA_RateGroup4_Female) VALUES("","","","","","","")